name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

env:
  NODE_VERSION: '22'

jobs:
  test_db_job:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    name: Test Database Job
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.4.0
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    - name: Install Dependencies
      run: |
        npm ci
    - name: Start Supabase
      run: |
        npm run supabase:start
    - name: Run Tests
      run: |
        npm run supabase:test:db

  deploy_db_job:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Deploy Database Job
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.PRODUCTION_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.PRODUCTION_PROJECT_ID }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.4.0
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    - name: Install Dependencies
      run: |
        npm ci
    - name: Link to Supabase project
      run: |
        npm run supabase:link ${{ secrets.PRODUCTION_PROJECT_ID }}
    - name: Push Database Changes
      run: |
        npm run supabase:db:push

  build_and_deploy_prod_job:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    needs:
    - deploy_db_job
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Build And Deploy
      id: builddeploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ICY_WAVE_0B7EE0603 }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "/"
        api_location: ".output/server"
        output_location: ".output/public"
