name: Azure Static Web Apps Close PR

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  close_pull_request:
    runs-on: ubuntu-latest
    name: Close Pull Request
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
          app_location: "/src" # App source code path
